server:
  port: 9090
  spring:
spring:  datasource:    username: sa
    password: null
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:    properties:      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  mvc:    view:      prefix: /views/
      suffix: .jsp
  mail:    host: smtp.gmail.com
    port: 587
    username: sanketbamane49@gmail.com
    password: a9890105455
    properties:      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          
 